### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by AmeliReyesHernandez** [SistemasTecTlaxiaco/actividad-1-infografia-AmeliReyesHernandez#1]
![IMG-20240902-WA0000](https://github.com/user-attachments/assets/4f9b524b-1026-43d2-b463-109596430f57)

**Comment by Diegocruz040708** [comment]
De acuerdo a la rubrica 
Calificación 19.5
Cuenta con 10 conceptos principales, los enlaces requeridos, visualmente correcto, buena ortografía 
Escasez de imágenes

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
